
version: '3.3'
services:
  eurekaserver:
    build: EurekaServer
    container_name: eurekacont
    image: eureka:1.0.0
    ports:
      - "8761:8761" 
    networks:
      - servicenet

  gatewayservice:
    build: Apigateway
    container_name: apicont
    image: api:1.0.0
    ports:
      - "9000:9000" 
    networks:
      - servicenet
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8761/eureka/
    depends_on:
      - eurekaserver
    links:
      - eurekaserver

  productservice:
    build: ProductService
    container_name: productcont
    image: product:1.0.0
    ports:
      - "8080:8080" 
    networks:
      - servicenet
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8761/eureka/
    depends_on:
      - eurekaserver
      - gatewayservice
    links:
      - eurekaserver

  orderservice:
    build: OrderService
    container_name: ordercont
    image: order:1.0.0
    ports:
      - "8081:8081" 
    networks:
      - servicenet
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8761/eureka/
    depends_on:
      - eurekaserver 
      - gatewayservice
      - productservice
    links:
      - eurekaserver
  
  inventoryservice:
    build: InventoryService
    container_name: inventorycont
    image: inventory:1.0.0
    ports:
      - "8082:8082" 
    networks:
      - servicenet
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8761/eureka/
    depends_on:
      - eurekaserver 
      - gatewayservice
      - productservice
      - orderservice
    links:
      - eurekaserver

networks:
  servicenet:
    driver: bridge 
  
